#pragma once

#include <seika/macro_utils.h>

#define CRE_VERSION_MAJOR 0
#define CRE_VERSION_MINOR 19
#define CRE_VERSION_PATCH 0

#define CRE_CORE_VERSION (SKA_MACRO_TO_STRING(CRE_VERSION_MAJOR) "." SKA_MACRO_TO_STRING(CRE_VERSION_MINOR) "." SKA_MACRO_TO_STRING(CRE_VERSION_PATCH))
