site_name: Crescent Documentation
repo_url: https://github.com/Chukobyte/crescent
edit_uri: ""
site_description: Documentation for the Crescent Game Engine.
site_author: Chukobyte
copyright: 'Copyright &copy; 2022 Chukobyte'

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
  - Configuration: configuration/configuration.md
  - Python-API: python_api/python_api.md
