site_name: Roll Back Engine Docs
repo_url: https://github.com/Chukobyte/roll-back-engine
edit_uri: ""
site_description: Documentation for the Roll Back Game Engine.
site_author: Chukobyte
copyright: 'Copyright &copy; 2022 Chukobyte'

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
