site_name: Crescent Documentation
repo_url: https://github.com/Chukobyte/crescent
edit_uri: ""
site_description: Documentation for the Crescent Game Engine.
site_author: Chukobyte
copyright: 'Copyright &copy; 2022 Chukobyte'

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

theme:
  name: material

nav:
  - Introduction: index.md
  - Configuration: configuration/configuration.md
  - Python-API:
      - About: python_api/python_api.md
      - Assets: python_api/assets.md
      - Color: python_api/color.md
      - Math: python_api/math.md
