#pragma once

// Keyboard
#define INPUT_VALUE_ZERO "0"
#define INPUT_VALUE_ONE "1"
#define INPUT_VALUE_TWO "2"
#define INPUT_VALUE_THREE "3"
#define INPUT_VALUE_FOUR "4"
#define INPUT_VALUE_FIVE "5"
#define INPUT_VALUE_SIX "6"
#define INPUT_VALUE_SEVEN "7"
#define INPUT_VALUE_EIGHT "8"
#define INPUT_VALUE_NINE "9"

#define INPUT_VALUE_A "a"
#define INPUT_VALUE_B "b"
#define INPUT_VALUE_C "c"
#define INPUT_VALUE_D "d"
#define INPUT_VALUE_E "e"
#define INPUT_VALUE_F "f"
#define INPUT_VALUE_G "g"
#define INPUT_VALUE_H "h"
#define INPUT_VALUE_I "i"
#define INPUT_VALUE_J "j"
#define INPUT_VALUE_K "k"
#define INPUT_VALUE_L "l"
#define INPUT_VALUE_M "m"
#define INPUT_VALUE_N "n"
#define INPUT_VALUE_O "o"
#define INPUT_VALUE_P "p"
#define INPUT_VALUE_Q "q"
#define INPUT_VALUE_R "r"
#define INPUT_VALUE_S "s"
#define INPUT_VALUE_T "t"
#define INPUT_VALUE_U "u"
#define INPUT_VALUE_V "v"
#define INPUT_VALUE_W "w"
#define INPUT_VALUE_X "x"
#define INPUT_VALUE_Y "y"
#define INPUT_VALUE_Z "z"

#define INPUT_VALUE_LEFT "left"
#define INPUT_VALUE_RIGHT "right"
#define INPUT_VALUE_UP "up"
#define INPUT_VALUE_DOWN "down"

#define INPUT_VALUE_RETURN "return"
#define INPUT_VALUE_SPACE "space"
#define INPUT_VALUE_ESCAPE "esc"

#define INPUT_VALUE_F1 "f1"
#define INPUT_VALUE_F2 "f2"
#define INPUT_VALUE_F3 "f3"
#define INPUT_VALUE_F4 "f4"
#define INPUT_VALUE_F5 "f5"
#define INPUT_VALUE_F6 "f6"
#define INPUT_VALUE_F7 "f7"
#define INPUT_VALUE_F8 "f8"
#define INPUT_VALUE_F9 "f9"
#define INPUT_VALUE_F10 "f10"
#define INPUT_VALUE_F11 "f11"
#define INPUT_VALUE_F12 "f12"

// Joystick
#define INPUT_VALUE_JOYSTICK_BUTTON_A "joystick_button_a"
#define INPUT_VALUE_JOYSTICK_BUTTON_B "joystick_button_b"
#define INPUT_VALUE_JOYSTICK_BUTTON_X "joystick_button_x"
#define INPUT_VALUE_JOYSTICK_BUTTON_Y "joystick_button_y"
#define INPUT_VALUE_JOYSTICK_DPAD_LEFT "joystick_dpad_left"
#define INPUT_VALUE_JOYSTICK_DPAD_RIGHT "joystick_dpad_right"
#define INPUT_VALUE_JOYSTICK_DPAD_UP "joystick_dpad_up"
#define INPUT_VALUE_JOYSTICK_DPAD_DOWN "joystick_dpad_down"
#define INPUT_VALUE_JOYSTICK_START "joystick_start"
#define INPUT_VALUE_JOYSTICK_BACK "joystick_back"
#define INPUT_VALUE_JOYSTICK_LEFT_SHOULDER "joystick_left_shoulder"
#define INPUT_VALUE_JOYSTICK_RIGHT_SHOULDER "joystick_right_shoulder"
#define INPUT_VALUE_JOYSTICK_LEFT_ANALOG "joystick_left_analog"
#define INPUT_VALUE_JOYSTICK_RIGHT_ANALOG "joystick_right_analog"
#define INPUT_VALUE_JOYSTICK_LEFT_TRIGGER "joystick_left_trigger"
#define INPUT_VALUE_JOYSTICK_RIGHT_TRIGGER "joystick_right_trigger"
#define INPUT_VALUE_JOYSTICK_LEFT_ANALOG_LEFT "joystick_left_analog_left"
#define INPUT_VALUE_JOYSTICK_LEFT_ANALOG_RIGHT "joystick_left_analog_right"
#define INPUT_VALUE_JOYSTICK_LEFT_ANALOG_UP "joystick_left_analog_up"
#define INPUT_VALUE_JOYSTICK_LEFT_ANALOG_DOWN "joystick_left_analog_down"
#define INPUT_VALUE_JOYSTICK_RIGHT_ANALOG_LEFT "joystick_right_analog_left"
#define INPUT_VALUE_JOYSTICK_RIGHT_ANALOG_RIGHT "joystick_right_analog_right"
#define INPUT_VALUE_JOYSTICK_RIGHT_ANALOG_UP "joystick_right_analog_up"
#define INPUT_VALUE_JOYSTICK_RIGHT_ANALOG_DOWN "joystick_right_analog_down"
