#pragma once

#define INPUT_VALUE_ZERO "0"
#define INPUT_VALUE_ONE "1"
#define INPUT_VALUE_TWO "2"
#define INPUT_VALUE_THREE "3"
#define INPUT_VALUE_FOUR "4"
#define INPUT_VALUE_FIVE "5"
#define INPUT_VALUE_SIX "6"
#define INPUT_VALUE_SEVEN "7"
#define INPUT_VALUE_EIGHT "8"
#define INPUT_VALUE_NINE "9"

#define INPUT_VALUE_A "a"
#define INPUT_VALUE_B "b"
#define INPUT_VALUE_C "c"
#define INPUT_VALUE_D "d"
#define INPUT_VALUE_E "e"
#define INPUT_VALUE_F "f"
#define INPUT_VALUE_G "g"
#define INPUT_VALUE_H "h"
#define INPUT_VALUE_I "i"
#define INPUT_VALUE_J "j"
#define INPUT_VALUE_K "k"
#define INPUT_VALUE_L "l"
#define INPUT_VALUE_M "m"
#define INPUT_VALUE_N "n"
#define INPUT_VALUE_O "o"
#define INPUT_VALUE_P "p"
#define INPUT_VALUE_Q "q"
#define INPUT_VALUE_R "r"
#define INPUT_VALUE_S "s"
#define INPUT_VALUE_T "t"
#define INPUT_VALUE_U "u"
#define INPUT_VALUE_V "v"
#define INPUT_VALUE_W "w"
#define INPUT_VALUE_X "x"
#define INPUT_VALUE_Y "y"
#define INPUT_VALUE_Z "z"

#define INPUT_VALUE_LEFT "left"
#define INPUT_VALUE_RIGHT "right"
#define INPUT_VALUE_UP "up"
#define INPUT_VALUE_DOWN "down"

#define INPUT_VALUE_RETURN "down"
#define INPUT_VALUE_SPACE "space"
#define INPUT_VALUE_ESCAPE "esc"

#define INPUT_VALUE_F1 "f1"
#define INPUT_VALUE_F2 "f2"
#define INPUT_VALUE_F3 "f3"
#define INPUT_VALUE_F4 "f4"
#define INPUT_VALUE_F5 "f5"
#define INPUT_VALUE_F6 "f6"
#define INPUT_VALUE_F7 "f7"
#define INPUT_VALUE_F8 "f8"
#define INPUT_VALUE_F9 "f9"
#define INPUT_VALUE_F10 "f10"
#define INPUT_VALUE_F11 "f11"
#define INPUT_VALUE_F12 "f12"
