#pragma once

#include <seika/ecs/component.h>

// indices
extern SkaComponentIndex ANIMATED_SPRITE_COMPONENT_INDEX;
extern SkaComponentIndex SPRITE_COMPONENT_INDEX;
extern SkaComponentIndex TRANSFORM2D_COMPONENT_INDEX;
extern SkaComponentIndex COLOR_RECT_COMPONENT_INDEX;
extern SkaComponentIndex NODE_COMPONENT_INDEX;
extern SkaComponentIndex PARALLAX_COMPONENT_INDEX;
extern SkaComponentIndex PARTICLES2D_COMPONENT_INDEX;
extern SkaComponentIndex SCRIPT_COMPONENT_INDEX;
extern SkaComponentIndex TEXT_LABEL_COMPONENT_INDEX;
extern SkaComponentIndex COLLIDER2D_COMPONENT_INDEX;

// type flags
extern SkaComponentType ANIMATED_SPRITE_COMPONENT_TYPE;
extern SkaComponentType SPRITE_COMPONENT_TYPE;
extern SkaComponentType TRANSFORM2D_COMPONENT_TYPE;
extern SkaComponentType COLOR_RECT_COMPONENT_TYPE;
extern SkaComponentType NODE_COMPONENT_TYPE;
extern SkaComponentType PARALLAX_COMPONENT_TYPE;
extern SkaComponentType PARTICLES2D_COMPONENT_TYPE;
extern SkaComponentType SCRIPT_COMPONENT_TYPE;
extern SkaComponentType TEXT_LABEL_COMPONENT_TYPE;
extern SkaComponentType COLLIDER2D_COMPONENT_TYPE;
