#include "ecs_globals.h"

// indices
SkaComponentIndex ANIMATED_SPRITE_COMPONENT_INDEX = 0;
SkaComponentIndex SPRITE_COMPONENT_INDEX = 0;
SkaComponentIndex TRANSFORM2D_COMPONENT_INDEX = 0;
SkaComponentIndex COLOR_RECT_COMPONENT_INDEX = 0;
SkaComponentIndex NODE_COMPONENT_INDEX = 0;
SkaComponentIndex PARALLAX_COMPONENT_INDEX = 0;
SkaComponentIndex PARTICLES2D_COMPONENT_INDEX = 0;
SkaComponentIndex SCRIPT_COMPONENT_INDEX = 0;
SkaComponentIndex TEXT_LABEL_COMPONENT_INDEX = 0;
SkaComponentIndex COLLIDER2D_COMPONENT_INDEX = 0;
SkaComponentIndex TILEMAP_COMPONENT_INDEX = 0;

// type flags
SkaComponentType ANIMATED_SPRITE_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType SPRITE_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType TRANSFORM2D_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType COLOR_RECT_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType NODE_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType PARALLAX_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType PARTICLES2D_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType SCRIPT_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType TEXT_LABEL_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType COLLIDER2D_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
SkaComponentType TILEMAP_COMPONENT_TYPE = SKA_ECS_COMPONENT_TYPE_NONE;
