name: macosx-clang-build

on:
  pull_request:
    branches: [ main ]

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          brew install pkg-config

      - name: get cmake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
          cmakeVersion: "3.25.0"

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

      - name: run build
        uses: lukka/run-cmake@v10.7
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DIS_CI_BUILD=true']"
          buildPreset: 'ninja-multi-vcpkg'

      - name: run unit tests
        run: |
          echo "Running crescent engine tests!"
          ${{ github.workspace }}/builds/Debug/crescent_engine_test
          echo ""
          echo "Running crescent engine editor tests!"
          ${{ github.workspace }}/builds/Debug/crescent_engine_editor_test
