name: macosx-clang-release-build

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ main ]

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: install vcpkg
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: run build
        run: |
          cd ${{ github.workspace }}
          cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake -DIS_CI_BUILD="true"
          cmake --build .

      - name: run unit tests
        run: |
          cd ${{ github.workspace }}
          echo "Running seika tests!"
          ./seika_test
          echo ""
          echo "Running crescent engine tests!"
          ./crescent_engine_test

      - name: deploy artifacts
        run: |
          python3 --version
          python3 -m pip install google-auth google-api-python-client
          cd ${{ github.workspace }}
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" >> creds.json
          python3 ci/upload_to_gd.py ${{ github.workspace }}/crescent_engine ${{ github.workspace }}/creds.json ${{ secrets.GDRIVE_FOLDER_ID }} crescent_engine_macos
