name: macosx-test-build

on:
  push:
    branches: [ package_test ]

env:
  PYTHON_VERSION: 3.10.5

jobs:
  # MACOSX BUILD
  macosx-build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: install vcpkg
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: install dependencies
        run: |
          brew install pkg-config

      - name: run build
        run: |
          cd ${{ github.workspace }}
          cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake -DIS_CI_BUILD="true"
          cmake --build . --config Release
          mv crescent_engine crescent_engine_macosx
          chmod +x crescent_engine_macosx

      - name: run unit tests
        run: |
          cd ${{ github.workspace }}
          echo "Running seika tests!"
          ./seika_test
          echo ""
          echo "Running crescent engine tests!"
          ./crescent_engine_test

      - name: store engine binary
        uses: actions/upload-artifact@v3
        with:
          name: crescent_engine_macosx
          path: crescent_engine_macosx
          if-no-files-found: error
