name: macosx-clang-python-embedded-package

on:
  push:
    branches: [ package_em ]

env:
  BUILD_NUMBER: custom
  PYTHON_VERSION: 3.10.5

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: configure-env-vars
        run: |
          temp_py_version=$(echo ${{ env.PYTHON_VERSION }} |  grep -Eo "\d+\.\d+\.\d+")
          echo "PYTHON_MICRO_VERSION=$temp_py_version" >> $GITHUB_ENV
          echo "ARCH=${{ env.RUNNER_OS }}" >> $GITHUB_ENV

      - name: setup-dependencies
        run: |
          brew install dpkg bzip2 libffi gdbm ncurses sqlite zlib openssl wget pkg-config -q

      - name: download-python-source
        run: |
          curl --fail -L https://www.python.org/ftp/python/${{ env.PYTHON_MICRO_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz -o Python-${{ env.PYTHON_VERSION }}.tgz
          tar zxf Python-${{ env.PYTHON_VERSION }}.tgz
          echo "current dir"
          ls -la

      - name: configure-python
        run: |
          mkdir -p build
          cd Python-${{ env.PYTHON_VERSION }}
          ./configure --prefix=${{ github.workspace }}/build --enable-optimizations --enable-ipv6 --enable-shared --without-ensurepip 2>&1 | tee -a ../python-${{ env.PYTHON_VERSION }}.config.log
          echo "config log"
          cat ../python-${{ env.PYTHON_VERSION }}.config.log
          echo "printout our dir"
          ls -la

      - name: compile-python
        run: |
          cd Python-${{ env.PYTHON_VERSION }}
          make

      - name: install-python
        run: |
          cd Python-${{ env.PYTHON_VERSION }}
          sudo make install

      - name: deploy-python
        run: |
          python3 --version
          python3 -m pip install google-auth google-api-python-client
          echo "printout our build dir"
          ls -la build
          tar -czvf python-build-${{ env.PYTHON_VERSION }}.tar.gz build
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" >> creds.json
          python3 ci/upload_to_gd.py python-build-${{ env.PYTHON_VERSION }}.tar.gz ${{ github.workspace }}/creds.json ${{ secrets.GDRIVE_FOLDER_ID }} python-macosx-build-${{ env.PYTHON_VERSION }}.tar.gz
