name: macosx-clang-python-embedded-package

on:
  push:
    branches: [ package_em ]

env:
  BUILD_NUMBER: custom
  PYTHON_VERSION: 3.10.5

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: configure-env-vars
        run: |
          echo "PYTHON_MICRO_VERSION=$(echo ${{ env.PYTHON_VERSION }} |  grep -Po "\d+\.\d+\.\d+")" >> $GITHUB_ENV
          echo "ARCH=${{ env.RUNNER_OS }}" >> $GITHUB_ENV

      - name: setup-dependencies
        run: |
          brew install dpkg bzip2 libffi gdbm ncurses sqlite libuuid zlib  -y

      - name: download-python-source
        run: |
          curl --fail -L https://www.python.org/ftp/python/${{ env.PYTHON_MICRO_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz -o Python-${{ env.PYTHON_VERSION }}.tgz
          ls -la
