name: macosx-clang-build

on:
  pull_request:
    branches: [ main ]

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          brew install pkg-config

      - name: get cmake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
          cmakeVersion: "3.27.0"

      - name: run build
        run: |
          cd ${{ github.workspace }}
          cmake . -DIS_CI_BUILD="true"
          cmake --build .

      - name: run unit tests
        run: |
          echo "Running crescent engine tests!"
          ${{ github.workspace }}/builds/Debug/crescent_engine_test
          echo ""
          echo "Running crescent engine editor tests!"
          ${{ github.workspace }}/builds/Debug/crescent_engine_editor_test
