name: macosx-clang-sign-test

on:
  push:
    branches: [ dev ]

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: installing vcpkg
        run: |
          echo "${{ secrets.MAC_CERT_KEY }}" >> cert.txt
          echo "${{ secrets.MAC_PKEY }}" >> pkey.txt
          base64 -D -i cert.txt -o cert.cer
          base64 -D -i pkey.txt -o private.key
          # Setup keychain stuff
          security create-keychain -p '${{ secrets.MAC_KEYCHAIN_PASS }}' build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p '${{ secrets.MAC_KEYCHAIN_PASS }}' build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          # Import Private Key
          security import private.key -P "${{ secrets.PRIVATE_KEY_PASSWORD }}" -A -t rsa -k build.keychain
          # Import Cert
          security import cert.cer -P "${{ secrets.CERTIFICATE_PASSWORD }}" -A -t cert -k build.keychain
          # Set up code signing
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.MAC_KEYCHAIN_PASS }}" build.keychain
          security find-identity -v -p codesigning build.keychain
          # Sign app
          touch text.txt
          codesign -s "${{ secrets.DEVELOPER_IDENTITY }}" -v test.txt

#      - name: installing vcpkg
#        run: |
#          cd ..
#          git clone https://github.com/Microsoft/vcpkg.git
#          cd vcpkg
#          ./bootstrap-vcpkg.sh
#
#      - name: install dependencies
#        run: |
#          brew install pkg-config
#
#      - name: run build
#        run: |
#          cd ${{ github.workspace }}
#          cmake . -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake -DIS_CI_BUILD="true"
#          cmake --build .
#
#      - name: run unit tests
#        run: |
#          cd ${{ github.workspace }}
#          echo "Running seika tests!"
#          ./seika_test
#          echo ""
#          echo "Running crescent engine tests!"
#          ./crescent_engine_test
