name: pvs-studio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  PVS-Studio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install updates
        run: |
          sudo apt install gcc-11
          sudo apt install g++-11

      - name: installing pvs-studio
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          sudo apt update
          sudo apt install pvs-studio
          pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}   

      - name: get cmake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
          cmakeVersion: "3.25.0"

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.0
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'b619a233fbf7b2c9765fb4458f3ecb05bd3166e3'

      - name: run build
        uses: lukka/run-cmake@v10.7
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DIS_CI_BUILD=true', '-DCMAKE_EXPORT_COMPILE_COMMANDS=On']"
          buildPreset: 'ninja-multi-vcpkg'

      - name: run pvs studio
        run: |
          pvs-studio-analyzer analyze -f builds/compile_commands.json -j -e include -e docs -e assets -e test_games

      - name: convert pvs studio report
        run: |
          plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log

      - name: publish pvs studio report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
