name: pvs-studio

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  PVS-Studio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          sudo apt install gcc-11
          sudo apt install g++-11

      - name: installing pvs-studio
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          sudo apt update
          sudo apt install pvs-studio
          pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}   

      - name: get cmake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
          cmakeVersion: "3.27.0"

      - name: run build
        run: |
          cd ${{ github.workspace }}
          mkdir -p builds
          cmake -S . -B builds -DIS_CI_BUILD="true" -DCMAKE_EXPORT_COMPILE_COMMANDS=On
          cmake --build builds

      - name: run pvs studio
        run: |
          pvs-studio-analyzer analyze -f builds/compile_commands.json -j -e include -e docs -e assets -e test_games --disableLicenseExpirationCheck

      - name: convert pvs studio report
        run: |
          plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log

      - name: publish pvs studio report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
