name: test-env-vars

on:
  push:
    branches: [ dev ]

jobs:
  ubuntu-env-vars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          sudo apt install jq

      - name: set env vars
        run: |
          echo "CRESCENT_VERSION=$(jq -r '.version' vcpkg.json)" >> $GITHUB_ENV
          echo "PYTHON_VERSION=$(jq -r '.dependencies[] | select(.name == "python3") | ."version>="' vcpkg.json)" >> $GITHUB_ENV
          echo "PYTHON_MAJOR_MINOR_VERSION=$(echo $PYTHON_VERSION | grep -Po "\d+.\d+")" >> $GITHUB_ENV

      - name: print env vars
        run: |
          echo "CRESCENT_VERSION = ${{ env.CRESCENT_VERSION }}"
          echo "PYTHON_VERSION = ${{ env.PYTHON_VERSION }}"
          echo "PYTHON_MAJOR_MINOR_VERSION = ${{ env.PYTHON_MAJOR_MINOR_VERSION }}"

  macos-env-vars:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          brew install jq

      - name: set env vars
        run: |
          echo "CRESCENT_VERSION=$(jq -r '.version' vcpkg.json)" >> $GITHUB_ENV
          echo "PYTHON_VERSION=$(jq -r '.dependencies[] | select(.name == "python3") | ."version>="' vcpkg.json)" >> $GITHUB_ENV
          echo "PYTHON_MAJOR_MINOR_VERSION=$(echo $PYTHON_VERSION | grep -Eo "\d+.\d+")" >> $GITHUB_ENV

      - name: print env vars
        run: |
          echo "CRESCENT_VERSION = ${{ env.CRESCENT_VERSION }}"
          echo "PYTHON_VERSION = ${{ env.PYTHON_VERSION }}"
          echo "PYTHON_MAJOR_MINOR_VERSION = ${{ env.PYTHON_MAJOR_MINOR_VERSION }}"