name: test-env-vars

on:
  push:
    branches: [ dev ]

jobs:
  windows-env-vars:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          Invoke-WebRequest https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
          Move-Item jq.exe C:\Windows\System32\WindowsPowerShell\v1.0\
          $env:PATH += ';C:\Windows\System32\WindowsPowerShell\v1.0\'

      - name: set env vars
        run: |
          echo "CRESCENT_VERSION=$(jq -r '.version' vcpkg.json)" >> $GITHUB_ENV
#          $env:CRESCENT_VERSION="$(jq -r '.version' vcpkg.json)"
#          $env:PYTHON_PATH=$(jq -r '.dependencies[] | select(.name == "python3") | ."version>="' vcpkg.json)

      - name: print env vars
        run: |
          echo "CRESCENT_VERSION = ${{ env.CRESCENT_VERSION }}"
#          echo "PYTHON_VERSION = ${{ env.PYTHON_VERSION }}"

  ubuntu-env-vars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          sudo apt install jq

      - name: set env vars
        run: |
          echo "CRESCENT_VERSION=$(jq -r '.version' vcpkg.json)" >> $GITHUB_ENV
          python_version=$(jq -r '.dependencies[] | select(.name == "python3") | ."version>="' vcpkg.json)
          echo "PYTHON_VERSION=$python_version" >> $GITHUB_ENV
          python_major_minor=$(echo $python_version | grep -Po "\d+.\d+")
          echo "PYTHON_MAJOR_MINOR_VERSION=$python_major_minor" >> $GITHUB_ENV

      - name: print env vars
        run: |
          echo "CRESCENT_VERSION = ${{ env.CRESCENT_VERSION }}"
          echo "PYTHON_VERSION = ${{ env.PYTHON_VERSION }}"
          echo "PYTHON_MAJOR_MINOR_VERSION = ${{ env.PYTHON_MAJOR_MINOR_VERSION }}"

  macos-env-vars:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: |
          brew install jq

      - name: set env vars
        run: |
          echo "CRESCENT_VERSION=$(jq -r '.version' vcpkg.json)" >> $GITHUB_ENV
          python_version=$(jq -r '.dependencies[] | select(.name == "python3") | ."version>="' vcpkg.json)
          echo "PYTHON_VERSION=$python_version" >> $GITHUB_ENV
          python_major_minor=$(echo $python_version | grep -Eo "\d+.\d+")
          echo "PYTHON_MAJOR_MINOR_VERSION=$python_major_minor" >> $GITHUB_ENV

      - name: print env vars
        run: |
          echo "CRESCENT_VERSION = ${{ env.CRESCENT_VERSION }}"
          echo "PYTHON_VERSION = ${{ env.PYTHON_VERSION }}"
          echo "PYTHON_MAJOR_MINOR_VERSION = ${{ env.PYTHON_MAJOR_MINOR_VERSION }}"