name: ubuntu-gcc-release-build

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install updates
        run: |
          sudo apt install gcc-11
          sudo apt install g++-11
          wget -O cmake.sh https://cmake.org/files/v3.20/cmake-3.20.1-linux-x86_64.sh
          sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
          export PATH=/usr/local/bin:$PATH
          cmake --version

      - name: run build
        run: |
          pwd
          touch test.txt

      - name: deploy artifacts
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GDRIVE_ACCESS_TOKEN }}
          filename: "test.txt"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
          mirrorDirectoryStructure: "false"
