name: windows-msvc-build

on:
  pull_request:
    branches: [ vcpkg_cache ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: get cmake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
          cmakeVersion: "3.25.0"

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.0
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'b619a233fbf7b2c9765fb4458f3ecb05bd3166e3'

#      - name: installing vcpkg
#        run: |
#          cd ..
#          git clone https://github.com/Microsoft/vcpkg.git
#          cd vcpkg
#          .\bootstrap-vcpkg.bat

      - name: run build
        run: |
          cd ${{ github.workspace }}
          cmake . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake -DIS_CI_BUILD="true"
          cmake --build .

      - name: run unit tests
        run: |
          echo "Running seika tests!"
          cd ${{ github.workspace }}
          ${{ github.workspace }}\Debug\seika_test.exe
          echo ""
          echo "Running crescent engine tests!"
          ${{ github.workspace }}\Debug\crescent_engine_test.exe
          echo ""
          echo "Running crescent engine editor tests!"
          ${{ github.workspace }}\Debug\crescent_engine_editor_test.exe
