name: windows-mingw-build

on:
  push:
    branches: [ tmap ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        with:
          install: gcc make

      - name: install dependencies
        shell: msys2 {0}
        run: |
          (echo ""; echo "y") | pacman -S mingw-w64-x86_64-toolchain
          echo "y" | pacman -S mingw-w64-x86_64-cmake
          echo "y" | pacman -S mingw-w64-x86_64-SDL2
          echo "y" | pacman -S mingw-w64-x86_64-freetype

      - name: run build
        shell: msys2 {0}
        run: |
          cmake -G "MinGW Makefiles" . -DIS_CI_BUILD="true"
          cmake --build .

      - name: run unit tests
        shell: msys2 {0}
        run: |
          echo "Running crescent engine tests!"
          ./crescent_engine_test.exe
          echo ""
          echo "Running crescent engine editor tests!"
          ./crescent_engine_editor_test.exe
