name: windows-mingw-build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        with:
          install: gcc make

      - name: run build
        run: |
          (echo ""; echo "y") | pacman -S mingw-w64-x86_64-toolchain
          echo "y" | pacman -S mingw-w64-x86_64-cmake
          echo "y" | pacman -S mingw-w64-x86_64-SDL2
          echo "y" | pacman -S mingw-w64-x86_64-freetype
          echo "y" | pacman -S mingw-w64-x86_64-python
          cmake -G "MinGW Makefiles" . -DIS_CI_BUILD="true"
          cmake --build .

      - name: run unit tests
        run: |
          echo "Running seika tests!"
          cd ${{ github.workspace }}
          ${{ github.workspace }}\Debug\seika_test.exe
          echo ""
          echo "Running crescent engine tests!"
          ${{ github.workspace }}\Debug\crescent_engine_test.exe
          echo ""
          echo "Running crescent engine editor tests!"
          ${{ github.workspace }}\Debug\crescent_engine_editor_test.exe
